### ISSUE TITLE
coredns question

### ISSUE THREAD

**Issue by aceeric** [bserdar/kubernetes-the-hard-way#3]
Hello - this is not an issue - just asking for help.

I'm trying a variant of your tutorial - with CentOS 8 VMs and Virtualbox. I have - in my case - one worker node for now and I'm running coredns on that node. If I run alpine pod on that node, for me:
```
$ kubectl exec -ti alpine -- sh
/ # nslookup kubernetes
;; connection timed out; no servers could be reached

/ # cat /etc/resolv.conf 
search kube-system.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.32.0.10
options ndots:5

/ # ping 10.32.0.10
PING 10.32.0.10 (10.32.0.10): 56 data bytes
^C
--- 10.32.0.10 ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss
```
It seems reasonable to me that - since the name server can't be pinged it can't perform name resolution. I'm light on kubernetes networking but my understanding is kubernetes handles forwarding pod IP traffic to the host so the traffic can reach other pods on the node or be routed to other nodes. What I don't see documented in your tutorial or the hightower version is - what entity would be responsible for providing a route out of the alpine pod that I'm testing in over into the coredns pod on IP 10.32.0.10 since this has nothing to do with the pod cidr range? I think that's where I'm hung up. Thanks.

**Comment by bserdar** [comment]
The original of this tutorial, when I forked it, used flannel. My version uses kube-router. If you installed kube-router: checkout the kube-router website for more up to date documentation. That is an active project, and their updates broke my setup more than once. After some troubleshooting specific to kube-router setup at the nodes, I managed to get up and running, but it's been a while since I checked this tutorial, and it may be stale. 

Once file you should check is  /var/lib/kube-router/kubeconfig. I've had several incidents in which incorrect values in this file caused issues. Also, make sure you edit kube-router manifests correctly for your configuration.

I suggest you try making this work with one worker and one controller first, and then extend.

If you followed a mix of the original tutorial and my version and installed flannel, then check flannel docs to see what is wrong with it.

**Comment by aceeric** [comment]
Ok thank you.
